export interface GovtScheme {
  id: string;
  title: Record<string, string>;
  category: 'maternity' | 'critical' | 'pharmacy' | 'senior' | 'general';
  coverage: Record<string, string>;
  summary: Record<string, string>;
  eligibility: Record<string, string[]>;
  documents: Record<string, string[]>;
  howToApply: Record<string, string[]>;
  officialLink: string;
  helpline: string;
  badge: string;
}

export const GOVT_SCHEMES: GovtScheme[] = [
  {
    id: 'pmjay',
    title: {
      hi: 'आयुष्मान भारत (PM-JAY)',
      en: 'Ayushman Bharat (PM-JAY)',
      bn: 'আয়ুষ্মান ভারত (PM-JAY)',
      ta: 'ஆயுஷ்மான் பாரத் (PM-JAY)',
      te: 'ఆయుష్మాన్ భారత్ (PM-JAY)',
      mr: 'आयुष्मान भारत (PM-JAY)',
      gu: 'આયુષ્માન ભારત (PM-JAY)',
      kn: 'ಆಯುಷ್ಮಾನ್ ಭಾರತ್ (PM-JAY)',
      pa: 'ਆਯੁਸ਼ਮਾਨ ਭਾਰਤ (PM-JAY)',
    },
    category: 'critical',
    badge: '₹5 लाख निःशुल्क इलाज',
    coverage: {
      hi: '₹5,00,000 प्रति परिवार / प्रति वर्ष कैशलेस इलाज',
      en: '₹5,00,000 per family per year for secondary & tertiary hospital care',
      bn: 'প্রতি বছর পরিবার প্রতি ₹৫,০০,০০০ টাকা পর্যন্ত বিনামূল্যে চিকিৎসা',
      ta: 'ஆண்டுக்கு ஒரு குடும்பத்திற்கு ₹5,00,000 இலவச சிகிச்சை',
      te: 'సంవత్సరానికి కుటుంబానికి ₹5,00,00,00 ఉచిత వైద్యం',
      mr: 'प्रति कुटुंब दरवर्षी ₹५,००,००० मोफत उपचार',
      gu: 'દર વર્ષે પરિવાર દીઠ ₹૫,૦૦,૦૦૦ સુધીની મફત સારવાર',
      kn: 'ವರ್ಷಕ್ಕೆ ಕುಟುಂಬಕ್ಕೆ ₹5,00,000 ಉಚಿತ ಚಿಕಿತ್ಸೆ',
      pa: 'ਹਰ ਸਾਲ ਪਰਿਵਾਰ ਲਈ ₹5,00,000 ਤੱਕ ਮੁਫ਼ਤ ਇਲਾਜ',
    },
    summary: {
      hi: 'भारत सरकार द्वारा देश के गरीब एवं ग्रामीण परिवारों के लिए दुनिया की सबसे बड़ी स्वास्थ्य बीमा योजना।',
      en: 'World\'s largest government-funded health assurance scheme covering 12+ Crore vulnerable rural families.',
      bn: 'ভারতের দরিদ্র ও গ্রামীণ পরিবারের জন্য বিশ্বের সর্ববৃহৎ স্বাস্থ্য বীমা প্রকল্প।',
      ta: 'இந்தியாவின் ஏழை மற்றும் கிராமப்புற குடும்பங்களுக்கான உலகின் மிகப்பெரிய சுகாதார காப்பீட்டு திட்டம்.',
      te: 'పేద మరియు గ్రామీణ కుటుంబాల కోసం ప్రపంచంలోనే అతిపెద్ద ఉచిత ఆరోగ్య భరోసా పథకం.',
      mr: 'भारतातील गरीब व ग्रामीण कुटुंबांसाठी जगातील सर्वात मोठी मोफत आरोग्य विमा योजना.',
      gu: 'ਗ੍ਰਾਮੀਣ અને ਗਰੀਬ ਪਰਿਵਾਰਾਂ ਲਈ ਦੁਨੀਆ ਦੀ ਸਭ ਤੋਂ ਵੱਡੀ ਮੁਫ਼ਤ ਸਿਹਤ ਯੋਜਨਾ.',
      kn: 'ಬಡ ಮತ್ತು ಗ್ರಾಮೀಣ ಕುಟುಂಬಗಳಿಗೆ ಜಗತ್ತಿನ ಅತಿ ದೊಡ್ಡ ಉಚಿತ ಆರೋಗ್ಯ ಯೋಜನೆ.',
      pa: 'ਗਰੀਬ ਅਤੇ ਪੇਂਡੂ ਪਰਿਵਾਰਾਂ ਲਈ ਵਿਸ਼ਵ ਦੀ ਸਭ ਤੋਂ ਵੱਡੀ ਸਿਹਤ ਬੀਮਾ ਯੋਜਨਾ।',
    },
    eligibility: {
      hi: [
        'SECC 2011 डेटा के अनुसार BPL / कच्चे मकान वाले ग्रामीण परिवार',
        'आशा (ASHA) / आंगनवाड़ी कार्यकर्ता और उनके परिवार',
        '70 वर्ष या उससे अधिक आयु के सभी वरिष्ठ नागरिक'
      ],
      en: [
        'Rural families with kutcha houses as per SECC 2011 database',
        'ASHA & Anganwadi workers and their dependent families',
        'All senior citizens aged 70 years and above (Ayushman Vaya Vandana)'
      ]
    },
    documents: {
      hi: ['आधार कार्ड (Aadhaar Card)', 'राशन कार्ड (Ration Card)', 'मोबाइल नंबर'],
      en: ['Aadhaar Card', 'Ration Card', 'Active Mobile Number']
    },
    howToApply: {
      hi: [
        'नजदीकी सरकारी अस्पताल (PHC/CHC) या कॉमन सर्विस सेंटर (CSC) जाएं।',
        'आयुष्मान मित्र से अपना आयुष्मान कार्ड बनवाएं (निःशुल्क)।',
        'अस्पताल में भर्ती होने पर बिना पैसे दिए कार्ड दिखाएं।'
      ],
      en: [
        'Visit nearest Govt Hospital / PHC or Common Service Center (CSC).',
        'Get your Ayushman Card generated by the Ayushman Mitra.',
        'Show card at empaneled hospitals for instant 100% cashless care.'
      ]
    },
    officialLink: 'https://pmjay.gov.in',
    helpline: '14555'
  },
  {
    id: 'pm-matru-vandana',
    title: {
      hi: 'प्रधानमंत्री मातृ वंदना योजना (PMMVY)',
      en: 'Pradhan Mantri Matru Vandana Yojana (PMMVY)',
      bn: 'প্রধানমন্ত্রী মাতৃ বন্দনা যোজনা',
      ta: 'பிரதம மந்திரி மாத்ரு வந்தனா திட்டம்',
      te: 'ప్రధాన మంత్రి మాతృ వందన యోజన',
      mr: 'प्रधानमंत्री मातृ वंदना योजना',
      gu: 'પ્રધાનમંત્રી માતૃ વંદના યોજના',
      kn: 'ಪ್ರಧಾನ ಮಂತ್ರಿ ಮಾತೃ ವಂದನಾ ಯೋಜನೆ',
      pa: 'ਪ੍ਰਧਾਨ ਮੰਤਰੀ ਮਾਤਰੂ ਵੰਦਨਾ ਯੋਜਨਾ',
    },
    category: 'maternity',
    badge: '₹6,000 मातृ सहायता',
    coverage: {
      hi: 'गर्भवती महिलाओं को ₹6,00,0 बैंक खाते में प्रत्यक्ष वित्तीय सहायता',
      en: 'Direct Benefit Transfer (DBT) of ₹6,000 for pregnant & lactating mothers',
      bn: 'গর্ভবতী মায়েদের জন্য সরাসরি ব্যাঙ্কে ₹৬,০০০ আর্থিক সহায়তা',
      ta: 'கர்ப்பிணிப் பெண்களுக்கு வங்கிக் கணக்கில் ₹6,00,0 உதவி',
      te: 'గర్భిణీ స్త్రీల బ్యాంక్ ఖాతాలో నేరుగా ₹6,000 ఆర్థిక సహాయం',
      mr: 'गर्भवती महिलांच्या बँक खात्यात थेट ₹६,००० आर्थिक मदत',
      gu: 'સગર્ભા મહિલાઓના બેંક ખાતામાં સીધા ₹૬,૦૦૦ ની સહાય',
      kn: 'ಗರ್ಭಿಣಿಯರ ಬ್ಯಾಂಕ್ ಖಾತೆಗೆ ನೇರವಾಗಿ ₹6,00,0 ಉಚಿತ ಧನಸಹಾಯ',
      pa: 'ਗਰਭਵਤੀ ਔਰਤਾਂ ਦੇ ਬੈਂਕ ਖਾਤੇ ਵਿੱਚ ₹6,000 ਦੀ ਸਿੱਧੀ ਵਿੱਤੀ ਸਹਾਇਤਾ',
    },
    summary: {
      hi: 'गर्भावस्था के दौरान बेहतर पोषण और प्रसव के समय वित्तीय सुरक्षा प्रदान करने की राष्ट्रीय योजना।',
      en: 'Cash incentive for pregnant women and lactating mothers for better nutrition and institutional delivery.',
      bn: 'গর্ভকালীন পুষ্টি এবং নিরাপদ প্রসূতি পরিষেবার জন্য জাতীয় সাহায্য প্রকল্প।',
      ta: 'கர்ப்பகால ஊட்டச்சத்து மற்றும் பாதுகாப்பான பிரசவத்திற்கான நிதியுதவி திட்டம்.',
      te: 'గర్భధారణ సమయంలో మెరుగైన పోషకాహారం మరియు సురక్షిత ప్రసవం కోసం సహాయం.',
      mr: 'गर्भावस्थेत योग्य पोषण आणि सुरक्षित बाळंतपणासाठी राष्ट्रीय आर्थिक मदत.',
      gu: 'સગર્ભાવસ્થા દરમિયાન યોગ્ય પોષણ અને સુરક્ષિત ડિલિવરી માટેની યોજના.',
      kn: 'ಗರ್ಭಾವಸ್ಥೆಯಲ್ಲಿ ಪೌಷ್ಟಿಕ ಆಹಾರ ಮತ್ತು ಉಚಿತ ವೈದ್ಯಕೀಯ ನೆರವು.',
      pa: 'ਗਰਭ ਅਵਸਥਾ ਦੌਰਾਨ ਬਿਹਤਰ ਪੋਸ਼ਣ ਲਈ ਸਰਕਾਰੀ ਯੋਜਨਾ।',
    },
    eligibility: {
      hi: [
        'सभी गर्भवती महिलाएं एवं स्तनपान कराने वाली माताएं (पहले 2 बच्चों के लिए)',
        'आंगनवाड़ी में पंजीकृत महिलाएं'
      ],
      en: [
        'Pregnant women & lactating mothers for first 2 living children',
        'Registered with Anganwadi Center (AWC)'
      ]
    },
    documents: {
      hi: ['मां का आधार कार्ड', 'माता-पिता का बैंक पासबुक', 'MCP कार्ड (आंगनवाड़ी से)'],
      en: ['Mother\'s Aadhaar Card', 'Bank Passbook linked to Aadhaar', 'MCP Card (Anganwadi)']
    },
    howToApply: {
      hi: [
        'स्थानीय आंगनवाड़ी कार्यकर्ता (ASHA/Anganwadi) से संपर्क करें।',
        'PMMVY फॉर्म भरें और प्रसवपूर्व जांच (ANC) रसीद जमा करें।',
        'राशि 3 किश्तों में सीधे बैंक खाते में आएगी।'
      ],
      en: [
        'Contact local Anganwadi Worker or ASHA sister in your village.',
        'Fill PMMVY Application Form with ANC registration details.',
        'Financial aid will be transferred directly to Aadhaar-linked bank account.'
      ]
    },
    officialLink: 'https://pmmvy.wcd.gov.in',
    helpline: '104'
  },
  {
    id: 'janaushadhi',
    title: {
      hi: 'प्रधानमंत्री जन औषधि योजना',
      en: 'PM Bharatiya Janaushadhi Pariyojana',
      bn: 'প্রধানমন্ত্রী জন ঔষধি প্রকল্প',
      ta: 'பிரதம மந்திரி ஜன ഔஷதி திட்டம்',
      te: 'ప్రధాన మంత్రి జన్ ఔషధి పరియోజన',
      mr: 'प्रधानमंत्री जन औषधी योजना',
      gu: 'પ્રધાનમંત્રી જન ઔષધિ યોજના',
      kn: 'ಪ್ರಧಾನ ಮಂತ್ರಿ ಜನೌಷಧಿ ಯೋಜನೆ',
      pa: 'ਜਨ ਔਸ਼ਧੀ ਯੋਜਨਾ',
    },
    category: 'pharmacy',
    badge: '50%-90% सस्ती दवाएं',
    coverage: {
      hi: 'उच्च गुणवत्ता वाली जेनेरिक दवाएं 50% से 90% तक कम कीमत पर',
      en: 'Quality generic medicines & surgical items at 50% to 90% lower prices',
      bn: '৫০% থেকে ৯০% কম দামে উচ্চমানের জেনেরিক ওষুধ',
      ta: 'உயர்தர ஜெனரிக் மருந்துகள் 50% முதல் 90% குறைந்த விலையில்',
      te: '50% నుండి 90% తక్కువ ధరకే నాణ్యమైన జెనెరిక్ మందులు',
      mr: 'उच्च दर्जाची जेनेरिक औषधे ५०% ते ९०% कमी किमतीत',
      gu: 'ઉચ્ચ ગુણવત્તાવાળી જેનરિક દવાઓ ૫૦% થી ૯૦% ઓછી કિંમતે',
      kn: '50% ರಿಂದ 90% ಕಮ್ಮಿ ಬೆಲೆಯಲ್ಲಿ ಉತ್ತಮ ಗುಣಮಟ್ಟದ ಮದ್ದುಗಳು',
      pa: "50% ਤੋਂ 90% ਘੱਟ ਕੀਮਤ 'ਤੇ ਉੱਚ ਗੁਣਵੱਤਾ ਵਾਲੀਆਂ ਦਵਾਈਆਂ",
    },
    summary: {
      hi: 'देश भर के जन औषधि केंद्रों पर डायबिटीज, बीपी, हृदय और कैंसर की दवाएं बहुत कम दाम पर उपलब्ध।',
      en: 'Over 2000+ medicines and 300+ surgical items available at nominal cost at Jan Aushadhi Kendras.',
      bn: 'ডায়াবেটিস, প্রেশার ও হৃদরোগের ওষুধ অত্যন্ত সস্তা দামে সহজলভ্য।',
      ta: 'நீரிழிவு, இரத்த அழுத்தம் மற்றும் இதய நோய்களுக்கான மருந்துகள் குறைந்த விலையில்.',
      te: 'మధుమేహం, బిపి మరియు గుండె జబ్బుల మందులు అతి తక్కువ ధరకే లభించును.',
      mr: 'मधुमेह, बीपी आणि हृदयरोगाची औषधे अत्यंत रास्त दरात उपलब्ध.',
      gu: 'ડાયાબિટીસ, બીપી અને હૃદયરોગની દવાઓ ખૂબ જ સસ્તા દરે ઉપલબ્ધ.',
      kn: 'ಸಕ್ಕರೆ ಕಾಯಿಲೆ, ಬಿಪಿ ಮತ್ತು ಹೃದಯ ಸಂಬಂಧಿ ಮದ್ದುಗಳು ಅತ್ಯಂತ ಅಗ್ಗದಲ್ಲಿ.',
      pa: 'ਡਾਇਬਟੀਜ਼, ਬੀਪੀ ਅਤੇ ਦਿਲ ਦੀਆਂ ਦਵਾਈਆਂ ਬਹੁਤ ਘੱਟ ਕੀਮਤ \'ਤੇ ਮਿਲਦੀਆਂ ਹਨ।',
    },
    eligibility: {
      hi: ['भारत का कोई भी नागरिक (किसी पर्चे या कार्ड की शर्त नहीं)'],
      en: ['Open to all citizens of India without income restrictions']
    },
    documents: {
      hi: ['डॉक्टर का पर्चा (Prescription) - दवाओं के नाम हेतु'],
      en: ['Valid doctor prescription showing salt/generic medicine name']
    },
    howToApply: {
      hi: [
        'नजदीकी "जन औषधि केंद्र" पर जाएं (अस्पताल locator से खोजें)।',
        'डॉक्टर का पर्चा दिखाएं और 90% तक की बचत पर दवाएं पाएं।'
      ],
      en: [
        'Locate nearest "Jan Aushadhi Kendra" using our Hospital Finder.',
        'Present your doctor\'s prescription to buy medicines at up to 90% discount.'
      ]
    },
    officialLink: 'https://janaushadhi.gov.in',
    helpline: '1800-180-8080'
  }
];
